In [1]:
import torch

In [11]:
a = torch.zeros(2, 2, 3, 3)

In [12]:
a

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [13]:
a.shape

torch.Size([2, 2, 3, 3])

In [15]:
b = torch.ones(2, 3, 3)

In [19]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [17]:
a[range(2), range(2)] += b

In [18]:
a

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [20]:
a.shape

torch.Size([2, 2, 3, 3])

In [21]:
N, _, D, _ = a.shape
a.permute(0, 2, 1, 3)

tensor([[[[1., 1., 1.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 1.]]]])

In [ ]:
path = 'data/kni8nm/dataset_2175_kin8nm.arff'


In [1]:
import pandas as pd
from scipy.io import arff

def convert_arff_to_excel_csv(path, csv_path, excel_path):
    # Load the ARFF file
    data, meta = arff.loadarff(path)
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    
    # Decode byte strings into normal strings (if needed)
    str_df = df.select_dtypes([object])
    str_df = str_df.stack().str.decode('utf-8').unstack()
    for col in str_df:
        df[col] = str_df[col]
    
    # Save to CSV
    df.to_csv(csv_path, index=False)
    
    # Save to Excel
    df.to_excel(excel_path, index=False)

# Define the paths
path = 'data/kni8nm/dataset_2175_kin8nm.arff'
csv_path = 'output_dataset.csv'
excel_path = 'output_dataset.xls'

# Call the function
convert_arff_to_excel_csv(path, csv_path, excel_path)

AttributeError: Can only use .str accessor with string values!

In [5]:
def convert_arff_to_excel_csv(path, csv_path, excel_path):
    # Load the ARFF file
    data, meta = arff.loadarff(path)
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    
    # Check and decode byte strings to normal strings (if needed)
    for column in df.select_dtypes([object]).columns:
        if df[column].apply(lambda x: isinstance(x, bytes)).any():
            df[column] = df[column].str.decode('utf-8')
    
    # Save to CSV
    df.to_csv(csv_path, index=False)
    
    # Save to Excel
    df.to_excel(excel_path, index=False)

# Define the paths
path = 'data/kni8nm/dataset_2175_kin8nm.arff'
csv_path = 'data/kni8nm/dataset_2175_kin8nm.csv'
excel_path = 'data/kni8nm/dataset_2175_kin8nm.xlsx'

convert_arff_to_excel_csv(path, csv_path, excel_path)

In [7]:
path = 'data/autompg/auto-mpg.data'

In [8]:
# Assuming the .data file is space-separated, and using a custom na_values to handle '?'
df = pd.read_csv(path, delim_whitespace=True, na_values='?', 
                 names=['mpg', 'cylinders', 'displacement', 'horsepower', 
                        'weight', 'acceleration', 'model year', 'origin', 'car name'])

# Handling missing values in 'horsepower'
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')  # Convert to numeric and coerce errors to NaN
df['horsepower'].fillna(df['horsepower'].mean(), inplace=True)       # Fill NaNs with the mean of the column

# Define the output path for the .xlsx file
output_xlsx_path = path.replace('.data', '.xlsx')

# Save the dataframe to an Excel file
df.to_excel(output_xlsx_path, index=False)

print(f"Data has been converted to Excel and saved at: {output_xlsx_path}")

Data has been converted to Excel and saved at: data/autompg/auto-mpg.xlsx


In [10]:
# Define the path to your 'data.txt' file
txt_file_path = 'data/naval/data.txt'

# Define the path where you want the .xlsx file to be saved
xlsx_file_path = 'data/naval/data.xlsx'

# Assuming the data is space-separated and there are 18 columns as per the 'Features.txt' content
column_names = [
    'Lever position (lp)', 'Ship speed (v) [knots]', 'Gas Turbine shaft torque (GTT) [kN m]',
    'Gas Turbine rate of revolutions (GTn) [rpm]', 'Gas Generator rate of revolutions (GGn) [rpm]',
    'Starboard Propeller Torque (Ts) [kN]', 'Port Propeller Torque (Tp) [kN]',
    'HP Turbine exit temperature (T48) [C]', 'GT Compressor inlet air temperature (T1) [C]',
    'GT Compressor outlet air temperature (T2) [C]', 'HP Turbine exit pressure (P48) [bar]',
    'GT Compressor inlet air pressure (P1) [bar]', 'GT Compressor outlet air pressure (P2) [bar]',
    'Gas Turbine exhaust gas pressure (Pexh) [bar]', 'Turbine Injecton Control (TIC) [%]',
    'Fuel flow (mf) [kg/s]', 'GT Compressor decay state coefficient',
    'GT Turbine decay state coefficient'
]

# Read the .txt file
df = pd.read_csv(txt_file_path, delim_whitespace=True, names=column_names, header=None)

# Save the DataFrame to an Excel file
df.to_excel(xlsx_file_path, index=False)

print(f'Data has been read from {txt_file_path} and saved as an Excel file at {xlsx_file_path}.')

Data has been read from data/naval/data.txt and saved as an Excel file at data/naval/data.xlsx.


In [11]:
df.head()

Lever position (lp)  Ship speed (v) [knots]  \
0                1.138                     3.0   
1                2.088                     6.0   
2                3.144                     9.0   
3                4.161                    12.0   
4                5.140                    15.0   

   Gas Turbine shaft torque (GTT) [kN m]  \
0                                289.964   
1                               6960.180   
2                               8379.229   
3                              14724.395   
4                              21636.432   

   Gas Turbine rate of revolutions (GTn) [rpm]  \
0                                     1349.489   
1                                     1376.166   
2                                     1386.757   
3                                     1547.465   
4                                     1924.313   

   Gas Generator rate of revolutions (GGn) [rpm]  \
0                                       6677.380   
1                                       6828.469   
2                                       7111.811   
3                                       7792.630   
4                                       8494.777   

   Starboard Propeller Torque (Ts) [kN]  Port Propeller Torque (Tp) [kN]  \
0                                 7.584                            7.584   
1                                28.204                           28.204   
2                                60.358                           60.358   
3                               113.774                          113.774   
4                               175.306                          175.306   

   HP Turbine exit temperature (T48) [C]  \
0                                464.006   
1                                635.401   
2                                606.002   
3                                661.471   
4                                731.494   

   GT Compressor inlet air temperature (T1) [C]  \
0                                         288.0   
1                                         288.0   
2                                         288.0   
3                                         288.0   
4                                         288.0   

   GT Compressor outlet air temperature (T2) [C]  \
0                                        550.563   
1                                        581.658   
2                                        587.587   
3                                        613.851   
4                                        645.642   

   HP Turbine exit pressure (P48) [bar]  \
0                                 1.096   
1                                 1.331   
2                                 1.389   
3                                 1.658   
4                                 2.078   

   GT Compressor inlet air pressure (P1) [bar]  \
0                                        0.998   
1                                        0.998   
2                                        0.998   
3                                        0.998   
4                                        0.998   

   GT Compressor outlet air pressure (P2) [bar]  \
0                                         5.947   
1                                         7.282   
2                                         7.574   
3                                         9.007   
4                                        11.197   

   Gas Turbine exhaust gas pressure (Pexh) [bar]  \
0                                          1.019   
1                                          1.019   
2                                          1.020   
3                                          1.022   
4                                          1.026   

   Turbine Injecton Control (TIC) [%]  Fuel flow (mf) [kg/s]  \
0                               7.137                  0.082   
1                              10.655                  0.287   
2                              13.086                  0.259   
3                              18.109        

In [1]:
path = 'data/parkinsons/parkinsons.data'

In [7]:
import pandas as pd
# Assuming the .data file is comma-separated and using a custom na_values to handle '?'
df = pd.read_csv(path, sep=',', na_values='?', 
                 names=['subject#', 'age', 'sex', 'test_time', 'motor_UPDRS', 
                        'total_UPDRS', 'Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 
                        'Jitter:PPQ5', 'Jitter:DDP', 'Shimmer', 'Shimmer(dB)', 
                        'Shimmer:APQ3', 'Shimmer:APQ5', 'Shimmer:APQ11', 
                        'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE', 'status'])

# Reordering the columns so that the target variable is the first variable
cols = list(df.columns)
cols = ['status'] + [col for col in cols if col != 'status']
df = df[cols]

# No missing values handling is shown in your request, but you can handle them similarly to the provided code

# Define the output path for the .xlsx file
output_xlsx_path = "data/parkinsons/parkinsons.xlsx"

# Save the dataframe to an Excel file
df.to_excel(output_xlsx_path, index=False)

print(f"Data has been converted to Excel and saved at: {output_xlsx_path}")

Data has been converted to Excel and saved at: data/parkinsons/parkinsons.xlsx
