In [1]:
import torch

In [11]:
a = torch.zeros(2, 2, 3, 3)

In [12]:
a

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [13]:
a.shape

torch.Size([2, 2, 3, 3])

In [15]:
b = torch.ones(2, 3, 3)

In [19]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [17]:
a[range(2), range(2)] += b

In [18]:
a

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [20]:
a.shape

torch.Size([2, 2, 3, 3])

In [21]:
N, _, D, _ = a.shape
a.permute(0, 2, 1, 3)

tensor([[[[1., 1., 1.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 1.]]]])

In [ ]:
path = 'data/kni8nm/dataset_2175_kin8nm.arff'


In [1]:
import pandas as pd
from scipy.io import arff

def convert_arff_to_excel_csv(path, csv_path, excel_path):
    # Load the ARFF file
    data, meta = arff.loadarff(path)
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    
    # Decode byte strings into normal strings (if needed)
    str_df = df.select_dtypes([object])
    str_df = str_df.stack().str.decode('utf-8').unstack()
    for col in str_df:
        df[col] = str_df[col]
    
    # Save to CSV
    df.to_csv(csv_path, index=False)
    
    # Save to Excel
    df.to_excel(excel_path, index=False)

# Define the paths
path = 'data/kni8nm/dataset_2175_kin8nm.arff'
csv_path = 'output_dataset.csv'
excel_path = 'output_dataset.xls'

# Call the function
convert_arff_to_excel_csv(path, csv_path, excel_path)

AttributeError: Can only use .str accessor with string values!

In [5]:
def convert_arff_to_excel_csv(path, csv_path, excel_path):
    # Load the ARFF file
    data, meta = arff.loadarff(path)
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    
    # Check and decode byte strings to normal strings (if needed)
    for column in df.select_dtypes([object]).columns:
        if df[column].apply(lambda x: isinstance(x, bytes)).any():
            df[column] = df[column].str.decode('utf-8')
    
    # Save to CSV
    df.to_csv(csv_path, index=False)
    
    # Save to Excel
    df.to_excel(excel_path, index=False)

# Define the paths
path = 'data/kni8nm/dataset_2175_kin8nm.arff'
csv_path = 'data/kni8nm/dataset_2175_kin8nm.csv'
excel_path = 'data/kni8nm/dataset_2175_kin8nm.xlsx'

convert_arff_to_excel_csv(path, csv_path, excel_path)

In [7]:
path = 'data/autompg/auto-mpg.data'

In [8]:
# Assuming the .data file is space-separated, and using a custom na_values to handle '?'
df = pd.read_csv(path, delim_whitespace=True, na_values='?', 
                 names=['mpg', 'cylinders', 'displacement', 'horsepower', 
                        'weight', 'acceleration', 'model year', 'origin', 'car name'])

# Handling missing values in 'horsepower'
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')  # Convert to numeric and coerce errors to NaN
df['horsepower'].fillna(df['horsepower'].mean(), inplace=True)       # Fill NaNs with the mean of the column

# Define the output path for the .xlsx file
output_xlsx_path = path.replace('.data', '.xlsx')

# Save the dataframe to an Excel file
df.to_excel(output_xlsx_path, index=False)

print(f"Data has been converted to Excel and saved at: {output_xlsx_path}")

Data has been converted to Excel and saved at: data/autompg/auto-mpg.xlsx


In [10]:
# Define the path to your 'data.txt' file
txt_file_path = 'data/naval/data.txt'

# Define the path where you want the .xlsx file to be saved
xlsx_file_path = 'data/naval/data.xlsx'

# Assuming the data is space-separated and there are 18 columns as per the 'Features.txt' content
column_names = [
    'Lever position (lp)', 'Ship speed (v) [knots]', 'Gas Turbine shaft torque (GTT) [kN m]',
    'Gas Turbine rate of revolutions (GTn) [rpm]', 'Gas Generator rate of revolutions (GGn) [rpm]',
    'Starboard Propeller Torque (Ts) [kN]', 'Port Propeller Torque (Tp) [kN]',
    'HP Turbine exit temperature (T48) [C]', 'GT Compressor inlet air temperature (T1) [C]',
    'GT Compressor outlet air temperature (T2) [C]', 'HP Turbine exit pressure (P48) [bar]',
    'GT Compressor inlet air pressure (P1) [bar]', 'GT Compressor outlet air pressure (P2) [bar]',
    'Gas Turbine exhaust gas pressure (Pexh) [bar]', 'Turbine Injecton Control (TIC) [%]',
    'Fuel flow (mf) [kg/s]', 'GT Compressor decay state coefficient',
    'GT Turbine decay state coefficient'
]

# Read the .txt file
df = pd.read_csv(txt_file_path, delim_whitespace=True, names=column_names, header=None)

# Save the DataFrame to an Excel file
df.to_excel(xlsx_file_path, index=False)

print(f'Data has been read from {txt_file_path} and saved as an Excel file at {xlsx_file_path}.')

Data has been read from data/naval/data.txt and saved as an Excel file at data/naval/data.xlsx.


In [11]:
df.head()

Lever position (lp)  Ship speed (v) [knots]  \
0                1.138                     3.0   
1                2.088                     6.0   
2                3.144                     9.0   
3                4.161                    12.0   
4                5.140                    15.0   

   Gas Turbine shaft torque (GTT) [kN m]  \
0                                289.964   
1                               6960.180   
2                               8379.229   
3                              14724.395   
4                              21636.432   

   Gas Turbine rate of revolutions (GTn) [rpm]  \
0                                     1349.489   
1                                     1376.166   
2                                     1386.757   
3                                     1547.465   
4                                     1924.313   

   Gas Generator rate of revolutions (GGn) [rpm]  \
0                                       6677.380   
1                                       6828.469   
2                                       7111.811   
3                                       7792.630   
4                                       8494.777   

   Starboard Propeller Torque (Ts) [kN]  Port Propeller Torque (Tp) [kN]  \
0                                 7.584                            7.584   
1                                28.204                           28.204   
2                                60.358                           60.358   
3                               113.774                          113.774   
4                               175.306                          175.306   

   HP Turbine exit temperature (T48) [C]  \
0                                464.006   
1                                635.401   
2                                606.002   
3                                661.471   
4                                731.494   

   GT Compressor inlet air temperature (T1) [C]  \
0                                         288.0   
1                                         288.0   
2                                         288.0   
3                                         288.0   
4                                         288.0   

   GT Compressor outlet air temperature (T2) [C]  \
0                                        550.563   
1                                        581.658   
2                                        587.587   
3                                        613.851   
4                                        645.642   

   HP Turbine exit pressure (P48) [bar]  \
0                                 1.096   
1                                 1.331   
2                                 1.389   
3                                 1.658   
4                                 2.078   

   GT Compressor inlet air pressure (P1) [bar]  \
0                                        0.998   
1                                        0.998   
2                                        0.998   
3                                        0.998   
4                                        0.998   

   GT Compressor outlet air pressure (P2) [bar]  \
0                                         5.947   
1                                         7.282   
2                                         7.574   
3                                         9.007   
4                                        11.197   

   Gas Turbine exhaust gas pressure (Pexh) [bar]  \
0                                          1.019   
1                                          1.019   
2                                          1.020   
3                                          1.022   
4                                          1.026   

   Turbine Injecton Control (TIC) [%]  Fuel flow (mf) [kg/s]  \
0                               7.137                  0.082   
1                              10.655                  0.287   
2                              13.086                  0.259   
3                              18.109        

In [1]:
path = 'data/parkinsons/parkinsons.data'

In [7]:
import pandas as pd
# Assuming the .data file is comma-separated and using a custom na_values to handle '?'
df = pd.read_csv(path, sep=',', na_values='?', 
                 names=['subject#', 'age', 'sex', 'test_time', 'motor_UPDRS', 
                        'total_UPDRS', 'Jitter(%)', 'Jitter(Abs)', 'Jitter:RAP', 
                        'Jitter:PPQ5', 'Jitter:DDP', 'Shimmer', 'Shimmer(dB)', 
                        'Shimmer:APQ3', 'Shimmer:APQ5', 'Shimmer:APQ11', 
                        'Shimmer:DDA', 'NHR', 'HNR', 'RPDE', 'DFA', 'PPE', 'status'])

# Reordering the columns so that the target variable is the first variable
cols = list(df.columns)
cols = ['status'] + [col for col in cols if col != 'status']
df = df[cols]

# No missing values handling is shown in your request, but you can handle them similarly to the provided code

# Define the output path for the .xlsx file
output_xlsx_path = "data/parkinsons/parkinsons.xlsx"

# Save the dataframe to an Excel file
df.to_excel(output_xlsx_path, index=False)

print(f"Data has been converted to Excel and saved at: {output_xlsx_path}")

Data has been converted to Excel and saved at: data/parkinsons/parkinsons.xlsx


In [4]:
import gzip
import numpy as np


SOURCE_URL = 'http://yann.lecun.com/exdb/mnist/'
WORK_DIRECTORY = 'data/mnist'
IMAGE_SIZE = 28
NUM_CHANNELS = 1
PIXEL_DEPTH = 255
NUM_LABELS = 10


In [5]:
def extract_data(filename, num_images):
  """Extract the images into a 4D tensor [image index, y, x, channels].
  Values are rescaled from [0, 255] down to [-0.5, 0.5].
  """
  print('Extracting', filename)
  with gzip.open(filename) as bytestream:
    bytestream.read(16)
    buf = bytestream.read(IMAGE_SIZE * IMAGE_SIZE * num_images)
    data = np.frombuffer(buf, dtype=np.uint8).astype(np.float32)
    #data = (data - (PIXEL_DEPTH / 2.0)) / PIXEL_DEPTH
    data = data.reshape(num_images, IMAGE_SIZE, IMAGE_SIZE, 1)
    return data


In [8]:
filename = 'data/mnist/t10k-images-idx3-ubyte/t10k-images-idx3-ubyte.gz'
extract_data(filename, 10)

Extracting data/mnist/t10k-images-idx3-ubyte/t10k-images-idx3-ubyte.gz


BadGzipFile: Not a gzipped file (b'\x00\x00')

In [11]:
from mlxtend.data import loadlocal_mnist
import platform


X, y = loadlocal_mnist(
            images_path='data/mnist/train-images.idx3-ubyte', 
            labels_path='data/mnist/train-labels.idx1-ubyte')

In [14]:
print('Dimensions: %s x %s' % (X.shape[0], X.shape[1]))
print('\n1st row', X[0])

Dimensions: 60000 x 784

1st row [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255
 247 127   0   0   0   0   0   0   0   0   0   0   0   0  30  36  94 154
 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0   0   0
   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82
  82  56  39   0   0   0   0   0   0   0   0   0   0   0   0  18 219 253
 253 253 253 253 1

In [15]:
import numpy as np

print('Digits:  0 1 2 3 4 5 6 7 8 9')
print('labels: %s' % np.unique(y))
print('Class distribution: %s' % np.bincount(y))

Digits:  0 1 2 3 4 5 6 7 8 9
labels: [0 1 2 3 4 5 6 7 8 9]
Class distribution: [5923 6742 5958 6131 5842 5421 5918 6265 5851 5949]


In [17]:
import pandas as pd
# Convert the loaded data into a DataFrame
data = pd.DataFrame(X)
data['label'] = y  # Adding labels as a new column in the DataFrame


In [18]:
data.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  label  
0    0      5  
1    0      0  
2    0      4  
3    0      1  
4    0      9  

[5 rows x 785 columns]

In [20]:
# Save the DataFrame to an Excel file
filename = 'data/mnist/mnist_data.xlsx'
data.to_excel(filename, index=False)
print(f'Data saved to {filename}')

Data saved to data/mnist/mnist_data.xlsx


In [21]:
data.head()

0  1  2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  781  782  \
0  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
1  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
2  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
3  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   
4  0  0  0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0   

   783  label  
0    0      5  
1    0      0  
2    0      4  
3    0      1  
4    0      9  

[5 rows x 785 columns]

In [23]:
import torch
from torch.nn.functional import one_hot
from sklearn.model_selection import train_test_split

def load_mnist_data(excel_path, test_size_split, seed, num_classes=10):
    # Load data from Excel file
    data = pd.read_excel(excel_path)
    
    # Assuming the last column in the DataFrame is 'label'
    X = data.iloc[:, :-1].values  # Features (pixel values)
    y = data.iloc[:, -1].values   # Labels

    # Normalize pixel values to be between 0 and 1
    X = X / 255.0

    # Reshape the images from 784 pixels to 28x28 (if necessary, depending on model input requirement)
    # Adding a channel dimension for grayscale
    X_reshaped = X.reshape(-1, 1, 28, 28)  # N, C, H, W format for PyTorch Conv2D

    # Convert labels and features into torch tensors
    X_tensor = torch.tensor(X_reshaped, dtype=torch.float32)
    y_tensor = torch.tensor(y, dtype=torch.long)

    # One-hot encode the labels
    y_one_hot = one_hot(y_tensor, num_classes=num_classes)

    # Split the data into training and testing sets
    x_train, x_test, y_train, y_test = train_test_split(X_tensor, y_one_hot, test_size=test_size_split, random_state=seed)
    
    return x_train, y_train, x_test, y_test

In [26]:
path = 'data/mnist/mnist_data.xlsx'
x_train, y_train, x_test, y_test = load_mnist_data(path, 0.2, 123)

In [27]:
x_train.shape

torch.Size([48000, 1, 28, 28])

In [28]:
y_train.shape

torch.Size([48000, 10])