In [1]:
import torch

In [11]:
a = torch.zeros(2, 2, 3, 3)

In [12]:
a

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [13]:
a.shape

torch.Size([2, 2, 3, 3])

In [15]:
b = torch.ones(2, 3, 3)

In [19]:
b

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [17]:
a[range(2), range(2)] += b

In [18]:
a

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [20]:
a.shape

torch.Size([2, 2, 3, 3])

In [21]:
N, _, D, _ = a.shape
a.permute(0, 2, 1, 3)

tensor([[[[1., 1., 1.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 1.]],

         [[0., 0., 0.],
          [1., 1., 1.]]]])